spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/hfparking?characterEncoding=utf-8
      username: root
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.cys.fmmall.entity

